### ISSUE TITLE
Refactor method `get_import_path`

### ISSUE THREAD

**Issue by Tara-Lakshmipathy** [pyiron/pyironFlow#30]
Currently the method has been copy-pasted from `reactflow.py` into `create_macro.py`. 

This method cannot be imported from `reactflow.py` into `create_macro.py` since `reactflow.py` itself imports `create_macro.py` which leads to circular import errors. 

One approach could be to have a new class with general methods (where we can start with this method and add more methods later) that could be useful in multiple places.

Thoughts @JNmpi, @liamhuber ?

**Comment by liamhuber** [comment]
IIRC `get_import_path` already fails for edge cases, e.g. where the `__qualname__` doesn't match the plain class name. I have a vague feeling I pulled out some similar functionality in snippets or workflow... I'll try to track that down.

**Comment by liamhuber** [comment]
Yeah, ok, what I was thinking of was `pyiron_snippets.factory._import_object`:

https://github.com/pyiron/pyiron_snippets/blob/076e38ff863749a9344f7da439de1f64d592bc98/pyiron_snippets/factory.py#L228-L233

Simply taking `__name__` can break when the object you want to import is nested inside something else, e.g.

```python
class Foo:
    class Bar:
        pass

Bar.__name__, Bar.__qualname__
>>> ('Bar', 'Foo.Bar')

```

If I have some such object in a module, it's critical that I have the full qualname in order to be able to access it -- with only the name I miss part of the necessary information.

More generally, I do find [`pyironflow.reactflow.get_import_path`](https://github.com/pyiron/pyironFlow/blob/93e6b4d5d57b59d45695d746feedad1d11b64f34/pyironflow/reactflow.py#L34-L41) a little bit sketchy in its hand-coded treatment of numpy arrays. I think part of what's going on here is that numpy arrays use a non-standard reconstructor. Failing for such cases is not unreasonable, and neither is having an exception for numpy arrays, but doing it by string comparison followed by string override feels fragile. I'm not familiar enough with the use cases here to be able to say how likely it is for this to bite you.

**Comment by liamhuber** [comment]
Switching name to qualname is probably not sufficient -- if the qualname is necessary you need to iterate on it. However the change doesn't _hurt_ because most of the time the two won't differ, and when they did name wouldn't have worked anyhow. So no harm, just doesn't solve the problem.

**Comment by JNmpi** [comment]
The purpose of import_path is to get the path for pyiron_node objects. It is not meant to be used on deeply nested object structures. Since the pyiron_nodes are well defined, there is no danger of running into these edge cases. To be on the safe side, we could give a warning if __name__ and __qualname__ are different and tell the user that this case is not implemented. Since the current function works fine for our purposes, I would not spend time extending it to cover an edge case that we will most likely never encounter.

**Comment by liamhuber** [comment]
> The purpose of import_path is to get the path for pyiron_node objects. It is not meant to be used on deeply nested object structures. Since the pyiron_nodes are well defined, there is no danger of running into these edge cases....Since the current function works fine for our purposes, I would not spend time extending it to cover an edge case that we will most likely never encounter.

I have a philosophical disagreement here. Users running into this edge case is as simple as them writing

```python
import pyiron_workflow as pwf

class MyNodeCollection:
    @pwf.as_function_node
    def SomeNode(x):
        return x + 1


class MyOtherCollection:
    @pwf.as_function_node
    def SomeOtherNode(x):
        return x - 1

```

At the end of the day, I think we want to invest a moderate amount of effort to minimize the amount of arbitrary "gotchas" limiting how users write their code. What is written above is not typical (aka edge case), but everything is perfectly well defined and reasonable there, yet would break the functionality here.

> To be on the safe side, we could give a warning if name and qualname are different and tell the user that this case is not implemented.

In light of developer time constraints, this feels like a perfectly reasonable compromise -- if they're behaving in a way we don't expect and can't handle, failure is a-ok as long as that failure is clean (and preferably informative).

**Comment by Tara-Lakshmipathy** [comment]
Based on the discussions here, I have reverted back to `__name__` and added a warning in case it differs from `__qualname__`. 

Based on @JNmpi's suggestion, I have renamed the additional file to [wf_extensions.py](https://github.com/pyiron/pyironFlow/blob/refactor-get_import_path/pyironflow/wf_extensions.py) and added the method `create_macro` here (since this is something that would eventually be in core workflow module).
